config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'student/index'=>'student#index'
  root 'student#index'

  post 'students'=>'tweets#create'
  

#resources :students, only :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def index
        @student=Student.all
    end

    def create
        student = Student(tweet_params)
        if student.save
            redirect_to :action => "index"
        else
            redirect_to :action => "index"
        end
    end

    private
    def tweet_params
        params.require(:tweet).permit(:body)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kobegeek</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>obegeek</h1>
<h3>学生情報</h3>

<%= form_for @student do |f| %>
    <div class="field">
        <%= f.label :body %>
        <%= f.text_field :body, :size => 140 %>
    </div>
    <%= f.submit "input" %>
<% end %>
<%= link_to "一覧に戻る", tweets_path %>


<%= link_to "新規投稿ページへ", students__path %>